// Autogenerated by go run example/gen/main.go. DO NOT EDIT.

// Package example is a simple example that uses autogen.
package example

const (
	// Sounds.

	// catSound is the name of the sound that cat does.
	catSound = "meow"
	// dogSound is the name of the sound that dog does.
	dogSound = "bark"

	// Name lengths.

	//catLen is the number of characters in the name cat.
	catLen = 3
	//dogLen is the number of characters in the name dog.
	dogLen = 3
)
